server:
  port: 4444
pulsar:
  service-url: pulsar://172.16.4.21:6650
spring:
  redis:
    host: 172.16.4.21
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: ENC(BHbvLrQJ+C7YTdCJUpINbb+utuQwsMYc2dCgqXBQCW5MMcsf+UWPllTU40xmSeBhKJ+av9XXTYNh6iXIexNeN/+Cd6yQ/mLUiin0evDyQu0iGRm0KLBvvEHITTlTB8BEAi3tKMhdIjOCj7L141GAn7vXEJUi12EJ3VjLPX74dVRrQarP3H4Y4pItFLV6nJ3HBbKjo/r1PiB/8zZhrTJp6014G0JS466igoSvQjwU9LongZnp5JgMIhH0Br8FVCuLkzNSgtDZ0RCSjA1xqwdGiE+/Kd8fkUzj6QifCoAV+yFgFYTxjvOoMLSWNrqPArCjWhQ+hqmhRC5HJEZmkMqBkgx83J12JKpCkqRZUFG7yRU=)
    username: ENC(WOJMqXEtNkQUXDhzNAWvBLvPKuzwYjIvuGdGJi577WlU9PboX+F1uBzRc1ipxhzo)
    password: ENC(UT4cva8Hen1q9a1JgDH5TFmQAiGpEmKk/a8/P/9ISLrMOYwdEths1fHi6wywPDRP)
    hikari:
      connection-test-query: select 'druid'
      minimum-idle: 1
      maximum-pool-size: 20
jasypt:
  encryptor:
    password: hKD28qYt6HedB57N